### ISSUE TITLE
work in browser?

### ISSUE THREAD

**Issue by francescoagati** [erelsgl/limdu#52]
can limdu work in a browser?
i get this error inside webpack

 ERROR  Failed to compile with 10 errors                                                                                                                                                14:49:43

These dependencies were not found:

* fs in C:/Users/franc/Documents/pror/~/limdu/classifiers/kNN/kNN.js, C:/Users/franc/Documents/pror/~/limdu/classifiers/svm/SvmPerf.js and 5 others
* child_process in C:/Users/franc/Documents/pror/~/limdu/classifiers/svm/SvmPerf.js, C:/Users/franc/Documents/pror/~/limdu/classifiers/svm/SvmLinear.js and 1 other

To install them, you can run: npm install --save fs child_process

**Comment by erelsgl** [comment]
Hi Francesco,
Most parts of limdu should work in browser. The exception is the SVM libraries, SvmLinear and SvmPerf, which depend on running a shell command using child_process. This is not possible to do from a browser. 
It could be nice to have a version of limdu that does not contain these libraries so that it is possible to use it in a browser, but I am not sure how to do this. A pull-request is welcome.

**Comment by francescoagati** [comment]
thanks,
i will try to study the code for make this pull request
